import subprocess

def nft(*args):
    return subprocess.run(["nft",*args],text=True,capture_output=True)

def authorize(ip):
    nft("add","element","inet","pisowifi","authorized_clients","{",ip,"}")

def deauthorize(ip):
    nft("delete","element","inet","pisowifi","authorized_clients","{",ip,"}")

def apply_speed(ip,mbps):
    # tc class/filter implementation is generated by tc_setup.py.
    subprocess.run(["/usr/local/sbin/pisowifi-tc","add",ip,str(mbps)],
                   text=True,capture_output=True)

def remove_speed(ip):
    subprocess.run(["/usr/local/sbin/pisowifi-tc","del",ip],
                   text=True,capture_output=True)
